default: &default
  adapter: postgresql
  encoding: unicode
  prepared_statements: false
  advisory_locks: false
<% if ENV.include?('DATABASE_URL') %>
  url: <%= ENV.fetch('DATABASE_URL') %>
<% end %>
<% if $0.include?('sidekiq') %>
  reaping_frequency: 10
  checkout_timeout: 5
  pool: 45 # Concurrency from sidekiq.yml
  variables:
    lock_timeout: 20s
<% elsif $0.include?('rake') %>
  connect_timeout: 5
  connect_timeout: 5
  variables:
    lock_timeout: 10s
<% else %>
  pool: <%= (ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 40) * 1.2 %>
  connect_timeout: 5
  checkout_timeout: 2
  reaping_frequency: 30
  variables:
    lock_timeout: 6s
    statement_timeout: 15s
<% end %>

development:
  primary:
    <<: *default
    database: kitsu_development
    database_tasks: false
  bypass_bouncer:
    <<: *default
    database: kitsu_development

test:
  primary:
    <<: *default
    database: kitsu_test
    database_tasks: false
  bypass_bouncer:
    <<: *default
    database: kitsu_test

production:
  primary:
    <<: *default
    database: kitsu_production
    database_tasks: false
  bypass_bouncer:
    <<: *default
    database: kitsu_production
    url: <%= ENV.fetch('DATABASE_URL_BYPASS_BOUNCER') %>
    variables:
      statement_timeout: '0'


staging:
  primary:
    <<: *default
    database: kitsu_staging
    database_tasks: false
  bypass_bouncer:
    <<: *default
    database: kitsu_staging
    url: <%= ENV.fetch('DATABASE_URL_BYPASS_BOUNCER') %>
    variables:
      statement_timeout: '0'
