name: 'Setup ImageMagick'
description: 'Setup a version of ImageMagick in your environment'
inputs:
  version:
    description: 'Version of ImageMagick to install'
    required: true
runs:
  using: "composite"
  steps:
      - name: Restore Cached ImageMagick ${{ inputs.version }}
        uses: actions/cache@v2
        id: cache-imagemagick
        with:
          path: .imagemagick-deb/
          key: ${{ runner.os }}-magick-rev3-${{ inputs.version }}

      - name: Install Cached ImageMagick ${{ inputs.version }}
        if: steps.cache-imagemagick.outputs.cache-hit == 'true'
        shell: bash
        run: |
          ls -l ./.imagemagick-deb/
          sudo apt install ./.imagemagick-deb/*.deb

      - name: Build ImageMagick ${{ inputs.version }}
        if: steps.cache-imagemagick.outputs.cache-hit != 'true'
        shell: bash
        run: |
          sudo apt remove imagemagick imagemagick-* -y
          t=$(mktemp)
          wget 'https://dist.1-2.dev/imei.sh' -qO "$t"
          sudo bash "$t" --checkinstall --imagemagick-version $IMAGEMAGICK_VERSION
          rm "$t"
          mkdir .imagemagick-deb
          ls -l /usr/local/src/
          cp /usr/local/src/*.deb ./.imagemagick-deb/
          ls -l ./.imagemagick-deb/
